#!/usr/bin/env python


# Written by Steines Fabien 
# 19-01-2016 

def writeListToFile(fileList,fileType,outputFile):
	
	# Count the number of elements in the List
	entryCount = len(fileList)

	# Loop through the List of Header Files
	for i in range(0,entryCount):
		
		# Check if this is the first element
		if i == 0:
			
			# Check if after the first element
			# there are more elements left 
			if (i+1) >= entryCount:
				outputFile.write (fileType + " += " + fileList[i] + "\n\n")
			else: 
				outputFile.write(fileType + " += " + fileList[i] + "\\\n")

		else:

			# Check if this is the last element
			if (i+1) >= entryCount:
				outputFile.write("\t" + fileList[i] + "\n\n")
			else: 
				outputFile.write("\t" + fileList[i] + "\\\n")
	


def scanFileAndConvert(inputFilePath):
	
	print("Scanning file: " + inputFilePath)
	
	# Define the empty lists
	uiFiles = []
	headerFiles = []
	sourceFiles = []
	
	# Open the source file
	inputFile = open(inputFilePath)
	fileContent = inputFile.readlines() 
	
	# First step: Excract the important Data from  the vcxproj source file 	
	for line in fileContent:
		
		# Remove the LineBreaks and Whitespaces from the line	
		lineContent = line.rstrip()
		
		# Conditions for the value string
		condition1 = ".ui" in lineContent or  ".h" in lineContent or ".cpp" in lineContent
		condition2 = "Include=" in lineContent  and not("GeneratedFiles" in lineContent)
		
		# Only proceed if the file applies to both conditions 
		if condition1 and condition2: 
			
			# Find the Index of the Value Data
			startIndex = lineContent.index("\"")
			endIndex = lineContent.rindex("\"")

			value = lineContent[startIndex + 1: endIndex ]
			if ".h" in value:
				headerFiles.append(value)
			else:
				if ".cpp" in value:
					sourceFiles.append(value)
				else: 
					uiFiles.append(value)

	# Close the Input File, it is no longer needed at this moment		
	inputFile.close()	

	# Sort the Header Files by Alphabethical Order
	headerFiles = sorted(headerFiles)
	# Sort the Source Files by Alphabethical Order
	sourceFiles = sorted(sourceFiles)
	# Sort the Header Files by Alphabethical Order
	uiFiles = sorted(uiFiles)

	# Outputting Data
	for filename in headerFiles: 
		print ("Header: " + filename)
	for filename in sourceFiles: 
		print("Source: " + filename)
	for filename in  uiFiles: 
		print("UI: " + filename)
	
	# Begin the Data Transformation part
	print ("\n")
	subStrings = inputFilePath.split(".")
	outputFileName = subStrings[0] + ".pro"
	
	print ("Writing Data to outputfile: " + outputFileName)	
	
	outputFile = open(outputFileName, 'w')
	
	# Write the base structure 
	# Please note that this still contains dummy code
	
	outputFile.write("#" + "-" * 40 + "\n")
	outputFile.write("# Qt Project File Generated by Ignis\n")
	outputFile.write("# Copyright by Steines Fabien 2016\n")
	outputFile.write("#" + "-" * 40 + "\n \n")

	outputFile.write("QT	+= Core Gui\n\n")
	outputFile.write("greaterThan(QT_MAJOR_VERSION, 4): QT += widgets\n")
	outputFile.write("TARGET = Ignis\n")
	outputFile.write("TEMPLATE = app\n\n")
	
	
	# Write the Different List to the Files
	writeListToFile(sourceFiles,"SOURCES",outputFile)
	writeListToFile(headerFiles,"HEADERS",outputFile)
	writeListToFile(uiFiles,"FORMS",outputFile)

	# Close the file
	outputFile.close()


	print ("\n")
	print("Done !")

scanFileAndConvert("Ignis.vcxproj")

